
DROP TABLE IF EXISTS Path;
DROP TABLE IF EXISTS is_in;

CREATE TABLE Path (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE is_in (
    id INTEGER,
    p_id INTEGER,
    ix INTEGER,
    FOREIGN KEY (id) REFERENCES Node (id),
    FOREIGN KEY (p_id) REFERENCES Path (id)
);


